plugins {
    id "java-library"
}

dependencies {

    implementation(project(":domain:metadata"))
    implementation(project(":domain:user"))
    implementation(project(":domain:util"))

    implementation("org.springframework:spring-context")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}